// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csfbqwpnxnrncnitwxfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzZmJxd3BueG5ybmNuaXR3eGZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDYyNTgsImV4cCI6MjA2MDAyMjI1OH0.KzdpjRtWnDppsr-KkurGbvqQNruUUldX49XsfCTEDEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);